[package]
name = "fuc"
version = "0.1.0"
authors = ["gzbakku <gzbakku@gmail.com>"]
edition = "2018"

[dependencies]

iron = "0.6.*"
plugin = "0.2"
persistent = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.83"
bodyparser = "0.8.0"
router = "*"
rust-crypto = "*"
rand = "*"
